# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stir' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'OneSignal', '~> 2.0'
  # Pods for Stir

  target 'StirTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
